# Copyright 2022 Mattermost, Inc.
name: "patch-version"
description: This action is used to patch package.json version with the nightly build

runs:
  using: "composite"
  steps:
    - name: ci/generate-version
      id: generate-version
      shell: bash
      run: go run ${{ github.action_path }}/patch-version.go .
